server:
  port: 9091
  servlet.context-path: /loans-evaluation-api

spring:
  application:
    name: loans-evaluation-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://X.Y.Z.W:8080/realms/loan-realm/protocol/openid-connect/certs

keycloak:
  resource: loans-evaluation-api

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE